services:
  hrm_web_app:
    image: hrm_web_app
    container_name: HRM_Web_App_container
    build:
      context: .
      dockerfile: HRM_Web_App/Dockerfile
  postgres:
    image: postgres:latest
    container_name: Postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 09122002
      POSTGRES_DB: AuthData
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./Repository/data_log/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis_container
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./Repository/data_base_log/redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s